### ISSUE TITLE
ESP Home Support 

### ISSUE THREAD

**Issue by grantstephens** [aerona-chofu-ashp/docs#1]
FYI: It is possible to monitor it using esphome and a Serial Port to RS485 UART Converter 
I have a gist of the config here: https://gist.github.com/grantstephens/e6604a4f20330c78443e59f69c12e3bb
Feel free to include it here somewhere if you think it would be useful.
This isn't technically an issue, so feel free to close it.

**Comment by tmarkettos** [comment]
Thanks! I've committed that to the modbus repo as https://github.com/aerona-chofu-ashp/modbus/commit/9782f8bf523c2a8b5dd309786fe94a49baa86dc8

Feel free to PR that repo if there's any more you'd like to add.

**Comment by caliston** [comment]
Thanks! I've committed that to the modbus repo as https://github.com/aerona-chofu-ashp/modbus/commit/9782f8bf523c2a8b5dd309786fe94a49baa86dc8

Feel free to PR that repo if there's any more you'd like to add.
